name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run "release-please"
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: keystone-keycloak-backend

      - name: Checkout project
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3

      - name: Setup Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v4
        with:
          cache: poetry

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: poetry build

      - name: Publish package distributions to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
